[profile.default]
src = "../contracts/src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/node_modules/@openzeppelin/contracts/",
    "@contracts/=../contracts/src/"
]
